version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
    # 集群名称
    - cluster.name=docker-cluster
    # 锁定内存，禁止内存换页
    - bootstrap.memory_lock=true
    # JVM参数
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:HeapDumpPath=/usr/share/elasticsearch/dump -XX:+UnlockDiagnosticVMOptions
    -XX:+PrintCompressedOopsMode -XX:ErrorFile=/usr/share/elasticsearch/dump/error.log -Dsun.net.inetaddr.ttl=30
    -Dsun.net.inetaddr.negative.ttl=10"
    # 修改挂载目录权限
    - TAKE_FILE_OWNERSHIP
    ulimits:
      # 内存锁定上限，单位KB
      memlock:
        # 不限制
        soft: -1
        hard: -1
      # 最大打开文件数不限制
      nofile:
        soft: -1
        hard: -1
      # 最大线程数不限制
      nproc:
        soft: -1
        hard: -1
    volumes:
    - ~/elasticsearch/data1:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch2
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:HeapDumpPath=/usr/share/elasticsearch/dump -XX:+UnlockDiagnosticVMOptions
    -XX:+PrintCompressedOopsMode -XX:ErrorFile=/usr/share/elasticsearch/dump -Dsun.net.inetaddr.ttl=30
    -Dsun.net.inetaddr.negative.ttl=10"
    # 集群中可连接的其他节点的列表
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
    # 符合成为master节点条件的最小节点数
    - "discovery.zen.ping.minimum_master_nodes=2"
    # 修改挂载目录权限
    - TAKE_FILE_OWNERSHIP
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - ~/elasticsearch/data2:/usr/share/elasticsearch/data
    networks:
    - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
